nginx:
  image: nginx
  volumes:
    - ./nginx-site.conf:/etc/nginx/conf.d/default.conf
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./data:/srv/http/nginx-site
  links:
    - php
  ports:
    - 80:80
php:
  image: nednisw/php-7.0.12-mysqli-fpm:latest
  volumes:
    - ./data:/srv/http/nginx-site
  links:
    - mysql:mysql
mysql:
  image: library/mysql
  volumes:
    - ./data/mysql:/var/lib/mysql
  ports:
    - 3306:3306
  environment:
    - MYSQL_ROOT_PASSWORD=supersecure
